### PR TITLE
pmix/dstore: fix the extention of the initial segment

### PR DESCRIPTION
**Pull request by karasevb**
Fixed problem discovered with `loop_spawn` test in PR #141

### CODE REVIEW

**Comment by karasevb** [comment]
@jjhursey please check

**Comment by jjhursey** [comment]
This branch passed all of the `ompi-tests/ibm/dynamic` tests including `loop_spawn`. Thanks!

Note for those that might test that `loop_spawn` took about 11 minutes to run to successful completion.

**Comment by artpol84** [comment]
@karasevb thanks!

**Comment by artpol84** [comment]
@karasevb please, PR this to 2.x branch ASAP!

**Pull request merged**
