### PR TITLE
Fix "pmix_info_t".

### PR DESCRIPTION
**Pull request by artpol84**

### CODE REVIEW

**Comment by artpol84** [comment]
Same change as https://github.com/pmix/releases/pull/10

**Comment by rhc54** [comment]
@artpol84 You'll need to make some changes in buffer_ops to silence warnings - already made the correct in the release version

See https://github.com/pmix/releases/commit/0d0a7b1bb5d01e82b507b8a75374dc8997bf1c7d

**Comment by artpol84** [comment]
Ok, will do tomorrow.

**Comment by artpol84** [comment]
@rhc54 warnings are fixed. Compiles cleanly.

**Comment by jjhursey** [comment]
This built correctly for me on my ppc64/ppc64le machines. 👍

**Pull request merged**
