### PR TITLE
Pr/issue 26

### PR DESCRIPTION
**Pull request by igor-ivanov**
Fix https://github.com/pmix/master/issues/26

Note: some tests require pmix internals. But now only PMIx API are exported in default configure. So use --disable-visibility to get tests built.

@rhc54 please look at

### CODE REVIEW

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by rhc54** [comment]
@igor-ivanov Sorry for being confused Tues morning - took me awhile to remember how disable-visibility worked. I think this looks fine, and using PMIX_EXPORT instead of DECLSPEC doesn't matter to me.

So once you rebase and resolve the conflicts...

:+1:

**Comment by igor-ivanov** [comment]
I think that people copy/past DECLSPEC w/o thinking about if it is needed. As a result there are many places with one. It was a reason I use PMIX_EXPORT. May be it is more informative.

**Comment by rhc54** [comment]
I'm the guilty party there - appreciate the cleanup!

**Pull request merged**
