### PR TITLE
misc OpenBSD 6 related fixes

### PR DESCRIPTION
**Pull request by ggouaillardet**
Thanks Paul Hargrove for bringing this to our attention

Refs open-mpi/ompi#2106

### CODE REVIEW

**Comment by rhc54** [comment]
@ggouaillardet If I read this correctly, we are indeed restoring the original LDFLAGS when we are done with searching - correct? I think it's important that we do so.

**Comment by rhc54** [comment]
I guess it also hits LIBS as well, but I gather we protect it too.

**Comment by ggouaillardet** [comment]
@rhc54 @PHHargrove this is correct
```_PMIX_CHECK_PACKAGE_LIB``` is an internal subroutine only invoked by ```PMIX_CHECK_PACKAGE```.
and in ```PMIX_CHECK_PACKAGE``` we do save and restore ```CPPFLAGS```, ```LDFLAGS``` and ```LIBS```

so i think we are good

**Comment by PHHargrove** [comment]
@ggouaillardet this resolves the issue that has been blocking my ability to test open-mpi/ompi#2107

**Comment by rhc54** [comment]
@ggouaillardet @PHHargrove  Thanks to both of you!

**Pull request merged**
