### PR TITLE
dist: do not include include/private/autogen/config.h in dist tarball

### PR DESCRIPTION
**Pull request by ggouaillardet**
this file is  automatically generated from include/private/autogen/config.h.in

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@rhc54 could you please review this ?

that solves one issue initially reported at http://www.open-mpi.org/community/lists/users/2016/01/28215.php
sun compiler uses config.h from the tarball (and that is good for gcc compiler) instead of config.h from the build directory (and that has been generated with sun compiler)

**Comment by ggouaillardet** [comment]
@rhc54 can you please review this ?

since ```top_srcdir``` is before ```top_builddir```, the wrong config.h (e.g. the one created when building the tarball) is used when building from a tarball __and__ when using VPATH.

that should be fine most of the time since the prominent platform is x86 / gcc, but we already got a report on the ompi ml (building v2.x from the tarball with sun compiler)

**Comment by rhc54** [comment]
@ggouaillardet All I see here is a copyright change - did you forget to push something?

**Comment by ggouaillardet** [comment]
i missed you already made the changes in pmix/master@14aa4fde8209b2e6463cd9cabedbab5354177af2

let's forget about the copyright and close this PR

**Pull request closed without merging**
