### PR TITLE
Fix buffer unpack hang

### PR DESCRIPTION
**Pull request by karasevb**
Сhery-picked from commit d8def6b (PR #125)

### CODE REVIEW

**Comment by karasevb** [comment]
@artpol84 please review

**Comment by artpol84** [comment]
@karasevb please update the commit comment with the as follows:
1. Name of commit should identify that you are fixing test suite, i.e. "test_suite: fir smoky test buffer unpack hang"
2. Fix the commit message describing the problem: 
* in what circumstances the problem appears
* why exactly the hang occurs.

**Comment by artpol84** [comment]
Ok, I talked to @karasevb and it is not a test fix. 
Good to go.

**Comment by artpol84** [comment]
@jjhursey please review and merge

**Pull request merged**
