### PR TITLE
Implemented error handler registration and notify fns and error handling bug fixes.

### PR DESCRIPTION
**Pull request by annu13**
Changes include
- support to register multiple error handler in client and server.
- notify errors from server to client and vice versa.
- select error handler for the error occurred.
- fixed bugs in server error notify

### CODE REVIEW

**Comment by mellanox-github** [comment]
* Coverity found 6 errors for pmix
* Coverity report at http://bgate.mellanox.com/jenkins/job/gh-pmix-pr//2/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rhc54** [comment]
@annu13 I have rebased and fixed the conflicts for you - see the attached file for the updated diff. You can simply replace these changesets with the new one.

I think overall this looks pretty good. Just a few suggestions:

* why have a specific error notification key for each type of notification? Why not just have an "PMIX_ERROR_NOTIFY_TYPE" key and then set the value to a string that indicates the type of desired data? You could even have it be a comma-delimited string of values, if you like. Might save some key definitions - on the other hand, the current definitions might be easier for users to understand as it is more specific.

* in pmix_client.c, line 80: you have a pmix_output that looks like a leftover debug. Should that be changed to pmix_output_verbose?

It's a pretty big change, and I don't know if we have time to really test it prior to release. Probably merits some discussion. So could you please update it and we'll hold it pending the discussion?

Thanks

[annu-update.txt](https://github.com/pmix/master/files/30576/annu-update.txt)

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by Di0gen** [comment]
bot:retest

**Comment by Di0gen** [comment]
bot:retest

**Comment by mellanox-github** [comment]
* Coverity found 4 errors for pmix
* Coverity report at http://bgate.mellanox.com/jenkins/job/gh-pmix-pr//10/Coverity_Report <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by annu13** [comment]
On 11/9/15, 7:45 PM, "rhc54" <notifications@github.com> wrote:

>@annu13 <https://github.com/annu13> I have rebased and fixed the
>conflicts for you - see the attached file for the updated diff. You can
>simply replace these changesets with the new one.
I forgot to rebase before pushing.. thank you for taking care of this. I
tried applying the new patch but it failed both using git and patch. So I
merged with upstream and pushed a new commit. Also I fixed a bug reported
in Jenkins and debug statements and silenced some compiler warnings. I
think it is good to go now :-).
>I think overall this looks pretty good. Just a few suggestions:
>
>* why have a specific error notification key for each type of
>notification? Why not just have an "PMIX_ERROR_NOTIFY_TYPE" key and then
>set the value to a string that indicates the type of desired data? You
>could even have it be a comma-delimited string of
> values, if you like. Might save some key definitions - on the other
>hand, the current definitions might be easier for users to understand as
>it is more specific.
yes I defined it this way to keep it easy to use.

>
>* in pmix_client.c, line 80: you have a pmix_output that looks like a
>leftover debug. Should that be changed to pmix_output_verbose?
yes. I fixed this and a few more in the server code.
>
>
>It's a pretty big change, and I don't know if we have time to really test
>it prior to release. Probably merits some discussion. So could you please
>update it and we'll hold it pending the discussion?
I am good either way. I did do a lot of testing to make sure it doesn�t
break the normal usage i.e. One error handler, no info keys and no notify
from client. I did functional testing of the new implementation but I
didn't stress test it with many permutations of keys and handlers.
I did fix a bug, where the error handling tag 0 recv was not handled as
persistent. I think we should bring that in, its a minor change.
Thanks,
Annu.

**Comment by rhc54** [comment]
@annu13 I fixed the merge conflicts and moved this to a branch on my fork of the master repo. We should avoid creating extra branches directly on the master

**Comment by annu13** [comment]
my bad. I created the branch inadvertently while fixing the merge conflicts. So would you be merging the changes into master for release 1.1.2?

**Comment by rhc54** [comment]
No, we were thinking of bringing it into 1.2.0 as it extends functionality without extending API. We are reserving 1.1.2 for simple bug fixes.

**Pull request closed without merging**
