### PR TITLE
test: fixed fence test

### PR DESCRIPTION
**Pull request by karasevb**
Fixed problem introduced in #146

### CODE REVIEW

**Comment by rhc54** [comment]
👍

**Comment by artpol84** [comment]
@karasevb please check if we need this in v2.x and PR if we do.

**Comment by artpol84** [comment]
please, note that v2.x now is in this (master) repository and not in the release repo.

**Comment by karasevb** [comment]
@artpol84 I checked it in master/v2.x, and it is does not required for fix there.

**Pull request merged**
