### PR TITLE
usock_connect() revamp

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@rhc54 can you please review this ?
then i will bring it into OpenMPI master

**Comment by rhc54** [comment]
The correct fix would be to just change the return value of the function to pmix_status_t - can we do that instead?

**Comment by ggouaillardet** [comment]
strictly speaking, we should change the prototype of this function.
when successful, it returns an int which is the file descriptor of the socket.
on error, it returns a pmix_status_t

I will fix that tomorrow

**Comment by ggouaillardet** [comment]
@rhc54 done !

**Comment by rhc54** [comment]
much better - thanks!

:+1:

**Pull request merged**
