### PR TITLE
dstor: pmix_esh: fix error handling.

### PR DESCRIPTION
**Pull request by artpol84**

### CODE REVIEW

**Comment by artpol84** [comment]
@karasevb please review

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
bot:retest

**Comment by jjhursey** [comment]
Is this also targeting v1.2?

**Comment by artpol84** [comment]
@jjhursey I think so.

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
bit:retest

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
@karasevb, please review

**Comment by artpol84** [comment]
bot:retest

**Comment by karasevb** [comment]
:thumbsup:

**Comment by artpol84** [comment]
@jjhursey @rhc54 please, have a look.
This PR cleanup's the dstore code with regard to error handling: more careful distinguish between fatal and normal errors is done.

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
I still need to fix it for PMI1/PMI2

**Comment by artpol84** [comment]
This is fine with respect to PMI1/PMI2. This issues will be addressed in the separate PR.

**Comment by artpol84** [comment]
I'm merging this so we can proceed.

**Comment by jjhursey** [comment]
@artpol84 @karasevb This needs to be PR'ed to v1.2.

**Comment by karasevb** [comment]
@jjhursey I'll do it

**Pull request merged**
