### PR TITLE
v1.2: dstor: pmix_esh: fix error handling.

### PR DESCRIPTION
**Pull request by karasevb**
This PR corresponds to PR #182

### CODE REVIEW

**Comment by karasevb** [comment]
bot:retest

**Comment by karasevb** [comment]
I changed some error codes against the original PR because them not supported in v1.2.
Namely:
```
-       rc = PMIX_ERR_FATAL;
+       rc = PMIX_ERROR;
```
```
-       rc = PMIX_ERR_NOT_AVAILABLE;
+       rc = PMIX_ERR_NOT_FOUND;
```
```
-       rc = PMIX_ERR_VALUE_OUT_OF_BOUNDS;
+       rc = PMIX_ERROR;
```
In this case (commit 45309df) I could not find a more suitable:
```
-       rc = PMIX_ERR_VALUE_OUT_OF_BOUNDS;
+       rc = PMIX_ERROR;
```

**Comment by karasevb** [comment]
@artpol84 @jjhursey please review

**Comment by artpol84** [comment]
:+1:

**Pull request merged**
