### PR TITLE
Get changes applied to 1.2

### PR DESCRIPTION
**Pull request by dsolt**
Same PR on master here applied to 1.2

### CODE REVIEW

**Comment by jjhursey** [comment]
Cherry-pick of the commit from PR #200 commit https://github.com/pmix/master/commit/be2098c85befa42ae2c825ff229a210aff7ab6de

**Comment by karasevb** [comment]
bot:retest

**Comment by jjhursey** [comment]
bot:retest

**Comment by jjhursey** [comment]
@karasevb @artpol84 I cannot tell from the CI test output where it is failing. It looks like a pass from what I can see. Can you take a look?

**Comment by artpol84** [comment]
@jjhursey yes, the output is confusing - we run all of the tests anyway but fail if saw at least one problem.

In this case the problem was for the compilations without dstore (see 16:52:35):
```
16:52:35 [jenkins03:22794] PMIX ERROR: BAD-PARAM in file src/client/pmix_client_get.c at line 374
16:52:35 [jenkins03:22795] PMIX ERROR: BAD-PARAM in file src/client/pmix_client_get.c at line 374
16:52:35 ERROR [test_fence.c:309:test_fence]: smoky_nspace-0:2: PMIx_Get failed: -46 from smoky_nspace-0:0, key key-f0:0
16:52:35 ERROR [test_fence.c:311:test_fence]: smoky_nspace-0:2: PMIx_Get failed (-1) from smoky_nspace-0:0
16:52:35 ERROR [pmix_client.c:132:main]: smoky_nspace-0:2 Fence test failed: -1
16:52:35 [jenkins03:22797] PMIX bfrop:unpack: got type 3 when expecting type 29
16:52:35 [jenkins03:22797] PMIX ERROR: PACK-MISMATCH in file src/client/pmix_client_get.c at line 374
16:52:35 ERROR [test_fence.c:309:test_fence]: smoky_nspace-0:1: PMIx_Get failed: -46 from smoky_nspace-0:0, key key-f0:0
16:52:35 ERROR [test_fence.c:311:test_fence]: smoky_nspace-0:1: PMIx_Get failed (-1) from smoky_nspace-0:0
16:52:35 ERROR [pmix_client.c:132:main]: smoky_nspace-0:1 Fence test failed: -1
16:52:35 ERROR [test_fence.c:309:test_fence]: smoky_nspace-1:3: PMIx_Get failed: -46 from smoky_nspace-0:0, key key-f0:0
16:52:35 ERROR [test_fence.c:311:test_fence]: smoky_nspace-1:3: PMIx_Get failed (-1) from smoky_nspace-0:0
16:52:35 ERROR [pmix_client.c:132:main]: smoky_nspace-1:3 Fence test failed: -1
16:52:35 ERROR [cli_stages.c:252:errhandler]:  PMIX server Error handler with status = -25
16:52:35 ERROR [cli_stages.c:252:errhandler]:  PMIX server Error handler with status = -25
16:52:35 ERROR [cli_stages.c:252:errhandler]:  PMIX server Error handler with status = -25
16:52:35 ERROR [pmix_client.c:48:errhandler]: PMIX client: Error handler with status = -25
16:52:35 ERROR [pmix_client.c:48:errhandler]: PMIX client: Error handler with status = -25
16:52:35 ERROR [pmix_client.c:48:errhandler]: PMIX client: Error handler with status = -25
16:52:35 ERROR [test_fence.c:309:test_fence]: smoky_nspace-0:0: PMIx_Get failed: -46 from smoky_nspace-0:1, key key-f0:0
16:52:35 ERROR [test_fence.c:311:test_fence]: smoky_nspace-0:0: PMIx_Get failed (-1) from smoky_nspace-0:1
16:52:35 ERROR [cli_stages.c:148:cli_cleanup]: rank 1 with state 1 unexpectedly terminated.
16:52:35 ERROR [pmix_client.c:132:main]: smoky_nspace-0:0 Fence test failed: -1
16:52:35 ERROR [pmix_test.c:175:main]: Test was aborted!
16:52:35 ERROR [cli_stages.c:252:errhandler]:  PMIX server Error handler with status = -25
```

**Comment by artpol84** [comment]
I actually wonder why it works fine with dstore. Can it be that David's change only affects non-dstore codepath?

**Comment by jjhursey** [comment]
This PR needs to be updated to address the CI failure. This will likely not make it for the initial v1.2 release. We can consider it for a v1.2.1 release if ready in time.

**Comment by jjhursey** [comment]
bot:retest

**Comment by jjhursey** [comment]
Per teleconf - we are not going to port this feature to the v1.2 series at this time. If there is demand for it then we can re-open this PR.

**Pull request closed without merging**
