### PR TITLE
PMIx Dynamic Plugin Support

### PR DESCRIPTION
**Pull request by rhc54**
Add the MCA plugin support infrastructure. Reorganize and flatten the public headers, removing all configure-generated references. Add frameworks for bfrops and sec to support cross-version operations.

### CODE REVIEW

**Comment by rhc54** [comment]
@artpol84 You'll need to update the Jenkins script so it runs autogen.pl instead of autogen.sh

**Comment by artpol84** [comment]
18:27:11 *** Making greek tarball
18:27:11 *** Running autogen ...
18:27:11 contrib/make_tarball: line 273: ./autogen.sh: No such file or directory
18:27:11 Autogen failed.  Aborting
18:27:11 + exit 11

Isn't it in make tarball?

I'll check

**Comment by rhc54** [comment]
@artpol84 Yes, it is in the tarball generating script - my bad. I'm correcting it now

**Comment by rhc54** [comment]
This is still going to fail as the util/keyval directory isn't getting added to the tarball - still investigating

**Comment by annu13** [comment]
@rhc54 This is really a big change, would it be possible to split it into multiple PRs  like a PR to bring in the base dynamic plugin support and PRs for individual frameworks for the community to be able to review.

**Comment by rhc54** [comment]
@annu13 I don't see how that can be done, I'm afraid - it would be impossible to verify that anything worked if it was split

**Comment by rhc54** [comment]
This includes:

Fixes #98

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
@rhc54 failure seems correct: munge component includes `<pmix/pmix_common.h>` while this file was moved directly into the `include` dir.

**Comment by rhc54** [comment]
@artpol84 I'm not trying to bring this one in anymore as-is, but will be replacing it with a series of commits instead. So I'll be "updating" it shortly once the MCA base infrastructure has been committed.

**Comment by jjhursey** [comment]
@rhc54 I think this is a stale PR - correct?
The mca infrastructure has already been merged in. So should this be closed?

**Comment by rhc54** [comment]
yes

**Pull request closed without merging**
