### PR TITLE
Code logic improvement

### PR DESCRIPTION
**Pull request by igor-ivanov**
Remove code that makes logic hard to understanding.
There is no needs in special processing here. Just use negative
values for special rank values.

@rhc54 could you review

### CODE REVIEW

**Comment by rhc54** [comment]
@igor-ivanov Hmmm...I really don't like seeing us setting a uint64 equal to a negative number. What is wrong with defining these "out-of-bound" values as INT_MAX and INT_MAX-1? We'll never see a rank that large.

The disconnect is due to the APIs all being defined as "int rank", while the hash table is using uint64. We don't know for certain the size of "int", though it usually defaults to 32-bits (in which case, we could just use the 32-bit version of the hash table class). I guess we could add a #if to pmix_common.h that says "if sizeof(int) is 32, define these values based on INT32_MAX - if sizeof(int) is 64, use the 64-bit version".

The rest of the change is okay with me - let's just avoid setting uint variables to negative values.

**Comment by igor-ivanov** [comment]
@rhc54 unsigned <-> signed operations should be fine.
will send some demo tomorrow.
I belive that changes are not critical but from my vision they make code clearer

**Comment by rhc54** [comment]
I have not issue with the basic changes - from a software engineering
point-of-view, I would rather that we not start setting uint variables to
negative values. It's just bad practice, so let's not start down that path.
In this case, it isn't necessary.

**Comment by igor-ivanov** [comment]
I got your point. Let follow current way. But probably to be consistent explicit translation for PMIX_RANK_WILDCARD should be added too in current code. What do you think?

Actually I do not see any issues using negative values on systems using two’s complement representation. As for me that using this make code unified.
Example:
```
#include <stdio.h>
#include <stdint.h>

int main(void)
{
    int val = -2;
    int16_t val_i16 = val;
    int32_t val_i32 = val;
    int64_t val_i64 = val;
    uint64_t val_u64;

    val_u64 = (uint64_t)val;
    printf("int=%d : 0x%X \t size=%d \t u64=%llu : 0x%llX\n", val, val, sizeof(val), val_u64, val_u64);

    val_u64 = (uint64_t)val_i16;
    printf("i16=%hd : 0x%hX \t size=%d \t u64=%llu : 0x%llX\n", val_i16, val_i16, sizeof(val_i16), val_u64, val_u64);
    val_u64 = (uint64_t)val_i32;
    printf("i32=%d : 0x%X \t size=%d \t u64=%llu : 0x%llX\n", val_i32, val_i32, sizeof(val_i32), val_u64, val_u64);
    val_u64 = (uint64_t)val_i64;
    printf("i64=%lld : 0x%llX \t size=%d \t u64=%llu : 0x%llX\n", val_i64, val_i64, sizeof(val_i64), val_u64, val_u64);

    val_u64 = (uint64_t)val;
    val = (int)val_u64;
    printf("int=%d : 0x%X\n", val, val);
    val_u64 = (uint64_t)val_i16;
    val_i16 = (int16_t)val_u64;
    printf("i16=%hd : 0x%hX\n", val_i16, val_i16);
    val_u64 = (uint64_t)val_i32;
    val_i32 = (int32_t)val_u64;
    printf("i32=%d : 0x%X\n", val_i32, val_i32);
    val_u64 = (uint64_t)val_i64;
    val_i64 = (int64_t)val_u64;
    printf("i64=%d : 0x%llX\n", val_i64, val_i64);

    return 0;
}
```
result:
```
$./a.out
int=-2 : 0xFFFFFFFE      size=4          u64=18446744073709551614 : 0xFFFFFFFFFFFFFFFE
i16=-2 : 0xFFFE          size=2          u64=18446744073709551614 : 0xFFFFFFFFFFFFFFFE
i32=-2 : 0xFFFFFFFE      size=4          u64=18446744073709551614 : 0xFFFFFFFFFFFFFFFE
i64=-2 : 0xFFFFFFFFFFFFFFFE      size=8          u64=18446744073709551614 : 0xFFFFFFFFFFFFFFFE
int=-2 : 0xFFFFFFFE
i16=-2 : 0xFFFE
i32=-2 : 0xFFFFFFFE
i64=-2 : 0xFFFFFFFFFFFFFFFE
```

**Comment by rhc54** [comment]
I suspect we are hitting some language issues here. I didn't say it won't
work - what I said is that it is poor programming practice. Once you start
getting sloppy about assigning negative values to unsigned variables, you
open the door to mistakes. Thus, deliberately making such assignments
should be avoided unless (a) you know with absolute certainty that it is
being correctly handled throughout the code (e.g., nobody is using the
value as an index into an array), and (b) there is no other way to
accomplish the task.

Neither of those cases is true here, so we should avoid it.

**Comment by igor-ivanov** [comment]
Removed negative vlaues usage from commit

**Pull request merged**
