### PR TITLE
V1.2 dstor pr10 (depends on #179)

### PR DESCRIPTION
**Pull request by artpol84**
Corresponds to PR #163.
Needs rebase once #179 is merged

### CODE REVIEW

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
@jjhursey I think we can start testing this PR.

**Comment by jjhursey** [comment]
I'll check out the branch today and run it though some MTT tests on our systems.

**Comment by jjhursey** [comment]
MTT running the `trivial` and `ibm` test suites passed clean (except for `ialltoall_in_place`, `ialltoallv_in_place`, and `iialltoallw_in_place` which fail with `MPI_ERR_ARG` - but that is an OMPI problem not related to PMIx).

Open MPI v2.x branch configured with:
```shell
./configure --enable-debug \
--with-pmix=$PMIX_INSTALL \
--with-libevent=$LIBEVENT_INSTALL \
--with-hwloc=$HWLOC_INSTALL
```

PMIx branch configured with:
```shell
./configure \
--with-libevent=$LIBEVENT_INSTALL \
--with-hwloc=$HWLOC_INSTALL \
--with-devel-headers \
--enable-dstore
```

👍 This looks good to merge

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
bot:retest

**Pull request merged**
