### PR TITLE
dstore: keeping job info in the dstor

### PR DESCRIPTION
**Pull request by karasevb**
Corresponds to PR #217

(cherry-picked from dcb6967da20b76ad357c3176f1fcfaa8807c8d2b)
(cherry-picked from 32c93e2bfddd23bc12cb098b56eb4859aedd6310)

### CODE REVIEW

**Comment by jjhursey** [comment]
Does PR #226 need to be pulled into this as well?

**Comment by artpol84** [comment]
@jjhursey yes you are right. We were waiting for the https://github.com/open-mpi/ompi/pull/2493 to verify that it is correct.
@karasevb please append this PR here as well.

**Comment by karasevb** [comment]
bot:retest

**Comment by artpol84** [comment]
@jjhursey I think it is ready to go.

**Pull request merged**
