### PR TITLE
dstore: Fix extension slot allocation

### PR DESCRIPTION
**Pull request by artpol84**
Signed-off-by: Artem Polyakov <artpol84@gmail.com>
(cherry picked from commit d9fcd4b7ca70ce737f1579ade0cfef21c4b0716e)

Conflicts:
	src/dstore/pmix_esh.c

### CODE REVIEW

**Comment by jjhursey** [comment]
I'm going to hold off merging this until @hjelmn has a chance to test PR #282 and confirm that it fixes Issue #280. Once we get the 👍  then I'll roll a `v1.2.1rc1`.

**Comment by jjhursey** [comment]
Per-teleconf. @artpol84 To run a test against his system. Once we get the 👍  from him then we are good to merge.

**Comment by artpol84** [comment]
@jjhursey good to go.

**Comment by jjhursey** [comment]
@artpol84 Thanks!

**Pull request merged**
