### PR TITLE
Attempt to resolve race condition

### LINKED ISSUE #89: possible PMIx server race: PMIx_server_register_client vs fence
As noted in #60, if a client enters a fence before all the clients on the same node have been registered with `PMIx_server_register_client()`, the fence will not complete.  This log snippet demonstrates the problem in a 16-node test.  Note rank 12 registers after one of the ranks calls fence.  This is because process launching and registration are done in parallel in the test server:
```
[jimbo:59144] recvd FENCE
[jimbo:59144] recvd fence with 1 procs
[jimbo:59144] get_tracker called with 1 procs
[jimbo:59144] new_tracker called with 1 procs
[jimbo:59144] get_tracker called with 1 procs
[jimbo:59144] adding new tracker with 1 procs
[jimbo:59144] new_tracker: all clients not registered nspace FLUX-START
snip
[jimbo:59144] pmix:server setup_fork for nspace FLUX-START rank 12
[jimbo:59144] pmix:server register client FLUX-START:12
[jimbo:59144] pmix:server _register_client for nspace FLUX-START rank 12
```

This can also be demonstrated with `pmix_test`.  I find the following hangs pretty reliably for me
```
./pmix_test -n 256 -e ./pmix_client
```
while with the patch below, I can run up to around `-n 800`, when I run out of file descriptors
```diff
diff --git a/test/utils.c b/test/utils.c
index 87c7e6a..b3fad58 100644
--- a/test/utils.c
+++ b/test/utils.c
@@ -183,16 +183,21 @@ int launch_clients(int num_procs, char *binary, char *** client_env, char ***bas
     myuid = getuid();
     mygid = getgid();
 
-    /* fork/exec the test */
+    /* register clients */
     for (n = 0; n < num_procs; n++) {
-        proc.rank = counter;
-        if (PMIX_SUCCESS != (rc = PMIx_server_setup_fork(&proc, client_env))) {//n
+        proc.rank = n;
+        if (PMIX_SUCCESS != (rc = PMIx_server_register_client(&proc, myuid, mygid, NULL, NULL, NULL))) {//n
             TEST_ERROR(("Server fork setup failed with error %d", rc));
             PMIx_server_finalize();
             cli_kill_all();
             return rc;
         }
-        if (PMIX_SUCCESS != (rc = PMIx_server_register_client(&proc, myuid, mygid, NULL, NULL, NULL))) {//n
+    }
+
+    /* fork/exec the test */
+    for (n = 0; n < num_procs; n++) {
+        proc.rank = counter;
+        if (PMIX_SUCCESS != (rc = PMIx_server_setup_fork(&proc, client_env))) {//n
             TEST_ERROR(("Server fork setup failed with error %d", rc));
             PMIx_server_finalize();
             cli_kill_all();
```

If it's required for all `PMIx_server_register_client()` calls to complete before processes are launched, this should be documented and the tests fixed as above.  o/w maybe it's a race that should be addressed elsewhere?

### PR DESCRIPTION
**Pull request by rhc54**
Fixes #89

### CODE REVIEW

**Comment by annu13** [comment]
@rhc54 I am not sure if it fixes the issue, because I think you still need to set trk->def_complete once all clients complete registration in reg client function. I am not sure, if this fix works  if the fence involves processes from different namespaces..

**Comment by garlick** [comment]
Is it useful for me to try this as is?  All clients would be in a single nspace in my test.

**Comment by rhc54** [comment]
Github’s issues are going to drive us nuts today, I fear :-(

Yes, go ahead and give it a try - since it was hanging for you before, let’s see if this at least fixes the problem you hit

**Comment by garlick** [comment]
Something not quite right.  This test failed on the second try:
```
./pmix_test -n 256 -e ./pmix_client
```

**Comment by rhc54** [comment]
By "second try", do you mean that the second client failed to connect somehow? Or that the first time the test ran to completion, but not when you tried it again?

**Comment by garlick** [comment]
I ran the test twice, first time worked, second time hung then timed out with
```
 ./pmix_test -n 256 -e ./pmix_client

ERROR [pmix_test.c:161:main]: Test exited by a timeout!
ERROR [cli_stages.c:148:cli_cleanup]: rank 0 with state 1 unexpectedly terminated.
ERROR [cli_stages.c:252:errhandler]:  PMIX server Error handler with status = -27
...
```

**Comment by rhc54** [comment]
@garlick Give this one a try - it works for me thru multiple attempts.

**Comment by garlick** [comment]
It seems good!  100 back to back runs of pmix_test as above succeeded.  My flux test that was failing works too.

**Comment by rhc54** [comment]
Excellent - thanks!

**Pull request merged**
