### PR TITLE
Set of fixes targeting restoration of PMI1/PMI2 support

### PR DESCRIPTION
**Pull request by artpol84**
With set of changes I was able to can run [MPICH 3.2](http://www.mpich.org/static/downloads/3.2/mpich-3.2.tar.gz) with SLURM 16.05 (branch from github + the fix with "volatile" as in Issue #279 ).

### CODE REVIEW

**Comment by artpol84** [comment]
@jjhursey needs to be backported to master. I'll open PR shortly.

**Comment by artpol84** [comment]
#286

**Comment by jjhursey** [comment]
We'll wait until PR #286 is confirmed to fix the issue, and merged in. Then I'll merge in this PR.

**Comment by artpol84** [comment]
@jjhursey you mean #284?

**Comment by jjhursey** [comment]
Sorry. It's Issue #286 - The PR to port this back to `master` hasn't been created yet.

As soon as we get confirmation that this fixes that issue then I'm fine with merging it in. I'd also like to have the PR against `master` in place too so this doesn't get lost.

**Comment by artpol84** [comment]
You are rigth, I'll create the PR asap.
Also - this PR solves the issue for me. So I guess we want it anyway. And there might be something on top for the #286.

**Comment by artpol84** [comment]
To make it clear: this PR is intended to fix MPICH support in PMIx. Since IMPI is based on MPICH it is definitely needed for #286.
I agree that it would be great if @JohnWestlund or @gdeisher can double check me with MPICH to confirm that this works.
However I wasn't trying to fully solve #286 with this PR, some further effort from @JohnWestlund and @gdeisher may be needed to verify/additional fix.

**Comment by artpol84** [comment]
@jjhursey I've created PR to the master. I can't check it with SLURM/pmix plugin as master is not yet supported. However the change is straightforward an I think we are fine here. Will try to check with some sample PMI tests.

**Comment by jjhursey** [comment]
Per discussion on the teleconf. Merging this in.

**Pull request merged**
