### PR TITLE
Fix some inconsistencies in pmix_status_t vs int declarations

### PR DESCRIPTION
**Pull request by jjhursey**
* Related to this PR on the release branch
   https://github.com/pmix/releases/pull/11

### CODE REVIEW

**Comment by jjhursey** [comment]
:bot:assign: @rhc54
:bot:label:bug
:bot:milestone:v2.0

**Comment by rhc54** [comment]
I do have to get that bot support running...sorry about that! Part of the problem is setting up a server to host the bot. Requires work over here.

**Comment by jjhursey** [comment]
No problem - force of habit I suppose. Could we use the Open MPI bot?

**Comment by rhc54** [comment]
Sure - need to coordinate with DongInn, I imagine. Would you be able to do so? Otherwise, I'd have to open a port on my home cluster to run the bot.

**Comment by rhc54** [comment]
👍

**Pull request merged**
