### PR TITLE
config: Consolidate private and public config.h to resolve C++ stdint.h issue

### PR DESCRIPTION
**Pull request by jjhursey**
Related to Issue #87 

This branch works, but I think the *true* fix will require a discussion about the configure logic and contents of the internal `config.h.in` and the external `config.h.in`.

### CODE REVIEW

**Comment by jjhursey** [comment]
@rhc54 Is there a reason why we have two different `config.h.in` files? The one that is installed does not include the `include/pmix/autogen/pmix_config_bottom.h` and `include/pmix/autogen/pmix_config_top.h` as I would expect it to, but the internal one does.

The `include/pmix/autogen/pmix_config_bottom.h` contained the STL fix for `stdint.h`, but when I included it it also needed all of the `HAVE_` macros that only seem to be defined in the internal `config.h.in` in `src/include/private/autogen/config.h.in`.

**Comment by rhc54** [comment]
It's purely historical, and the reason is no longer valid. At one time, we had a config.h in pmix_common to support some config-set values. We have since eliminated those (hooray!).

So I'd suggest we consolidate to one and avoid the problems.

**Comment by jjhursey** [comment]
I should also note that this patch will not always work since `pmix_stdint.h` is not where the installed `pmix_config_bottom.h` expects to find it: `<pmix/autogen/pmix_stdint.h>`

I can work on consolidating the header file as part of this ticket. I would want this to be in PMIx 1.1.4 - hopefully that won't be too bad to sort out later.

**Comment by jjhursey** [comment]
@rhc54 I did the config.h header consolidation. I can confirm that this resolves the C++ issue and builds on the few platforms I have access too. Can you review this PR before we merge it into the master?

Once it is merged into the master branch, it should probably soak there for a few days before pulling it over to the v1.1.4 rc branch. At which point I think it would be good to roll a new rc to get some broader testing.

**Comment by rhc54** [comment]
I think this look okay. IIRC, we were going to get rid of PMIX_DECLSPEC because of confusion it created. Instead, we use PMIX_EXPORT for symbols that should be externally visible, and don't use anything else. Should we clean that up here? Or do it separately?

**Comment by jjhursey** [comment]
I'm fine either way, as long as it comes in as a separate commit. Tomorrow, I can convert all of these over to `PMIX_EXPORT` and remove the `PMIX_DECLSPEC` symbol.

I just did a quick grep and it looks like both are used quite a bit:
```shell
shell$ grep -rnI "PMIX_EXPORT" * | wc -l
99
shell$ grep -rnI "PMIX_DECLSPEC" * | wc -l
103
```

**Comment by rhc54** [comment]
Let's do it separately, then.

👍

**Pull request merged**
