### PR TITLE
dstore: added check the return code of lock fcntl

### PR DESCRIPTION
**Pull request by karasevb**
cherry-picked from commit 7e530bf (PR #162)

### CODE REVIEW

**Comment by karasevb** [comment]
@artpol84 please review

**Comment by artpol84** [comment]
bot:retest

**Comment by karasevb** [comment]
Jenkins failed because of a know problem with dstor that we already fixed. This PR will wait until the porting a dstore fixes in another  PR.

**Comment by artpol84** [comment]
@karasevb please make sure that all needed PR's are ported to the v2.x

**Comment by jjhursey** [comment]
@karasevb Can you make a PR for this change to the v1.2 branch?

**Comment by jjhursey** [comment]
I'm going to close this ticket. We will recreate the v2.x branch from the v1.2 branch, which will pick up these changes (PR'ed to v1.2 branch in PR #195

**Pull request closed without merging**
