### PR TITLE
Fetch some info from the info array before initializing server base.

### PR DESCRIPTION
**Pull request by karasevb**
In particular, this fixes initialization of the 'mytmpdir'.

### CODE REVIEW

**Comment by karasevb** [comment]
@artpol84 please review.

**Comment by artpol84** [comment]
Ok, so the problem here is that `mytmpdir` is expected to be initialized in `initialize_server_base`:
https://github.com/pmix/master/blob/master/src/server/pmix_server.c#L186

But actual initialization of this variable is performed after  `initialize_server_base` in `PMIx_Server_init`:
https://github.com/pmix/master/blob/master/src/server/pmix_server.c#L299

**Comment by artpol84** [comment]
:+1:

**Comment by artpol84** [comment]
@rhc54 I think this is a minor fix so I'm merging it now. We need this fix for our dstor PR that we will merge later today.

**Comment by artpol84** [comment]
@karasevb please go ahead with the DSTOR merge

**Pull request merged**
