### PR TITLE
Disable the errhandler support as it is broken

### PR DESCRIPTION
**Pull request by rhc54**
will be restored in subsequent release series

Signed-off-by: Ralph Castain <rhc@open-mpi.org>

### CODE REVIEW

**Comment by rhc54** [comment]
Fixes #76

**Comment by artpol84** [comment]
@karasevb please check this branch in the environment where you were observing problems.

**Comment by artpol84** [comment]
@rhc54 For me it looks good, but let's give it a try at runtime as well.

**Comment by rhc54** [comment]
Just to be clear: the code referenced here is never called in Open MPI v2.0 or v2.x series branches. So this should only be an issue when testing PMIx itself.

**Comment by karasevb** [comment]
I checked, smoky test is now working well :+1:

**Comment by artpol84** [comment]
Thank you, @karasevb .

**Pull request merged**
