### PR TITLE
Update the PMIx_Finalize function to take an array of attributes.

### LINKED ISSUE #27: PMIx_Get() behaivour
I would like to share my observation related PMIx_Get() logic.
@rhc54 let think if it is an issue or not.

How to reproduce in pseudo code:
PMIx_Init()
rank=0 /* it should not be WILDCARD !!!*/
key="not exist value"
info=pmix.timeout
PMIx_Get()

Observation:
hang place https://github.com/pmix/master/blob/master/src/client/pmix_client_get.c#L101-L103

Logic:
* PMIx_Get()
* PMIx_Get_nb()
* _getnbfn() send message to server PMIX_GETNB_CMD: https://github.com/pmix/master/blob/master/src/client/pmix_client_get.c#L493-L500
* pmix_server_get()
* can not find data:
https://github.com/pmix/master/blob/master/src/server/pmix_server_get.c#L211
* return SUCCESS:
https://github.com/pmix/master/blob/master/src/server/pmix_server_get.c#L211
* hang https://github.com/pmix/master/blob/master/src/client/pmix_client_get.c#L101-L103

Possible reason:
no pmix_pending_resolve() calls that could be complete pending request.

Note:
- There is no communications with RM in this case.
- pmix.timeout is passed by a user

Question to discuss:
Is there any chance to track timeout in this case?

### PR DESCRIPTION
**Pull request by rhc54**
Define a new attribute PMIX_EMBED_BARRIER to tell the function to barrier before executing the finalize operation

Fixes #27

### CODE REVIEW

**Comment by igor-ivanov** [comment]
@rhc54 The first point I would like to discuss if default behaivour for PMIx_Finalize as w/ internal fence is more preferable. I do not have strong opinion here but we think about this.
After thinking more about this topic that one of the possible approaches could be changing PMIx_Init instead of PMIx_Finalize.
Let imagine that PMIx_Init has following signature: 
`pmix_status_t PMIx_Init(pmix_proc_t *proc, const pmix_info_t info[], size_t ninfo);`
In this case user could manipulate PMIx global logic on start.
Examples:
- pmix.fini.barrier - do barrier during PMIx_Finalize
- pmix.global.timeout - set timeout for all non blocking operations (do not bother for specific operations)
- etc
Please consider this notice as just point for thinking and may be discussing on next PMIx meeting.

**Comment by rhc54** [comment]
@igor-ivanov Let's think about the default on finalize - I still need to check what the prior PMI libraries do, or if you get a chance, perhaps you can check and let us know.

Adding info array to PMIx_Init makes sense for a variety of reasons, including symmetry. I can add that to this PR. Thanks!

**Comment by rhc54** [comment]
@igor-ivanov I have updated the PMIx_Init function signature and used it to pass an event_base into the library so OMPI (and possibly others) can reduce the thread count. Also did a bunch of cleanup. Please let me know so we can update OMPI to reflect the changes.

**Comment by artpol84** [comment]
@rhc54 This changes brakes SLURM plugin.
I thought that API changes has to be discussed!

**Comment by artpol84** [comment]
@rhc54 @jladd-mlnx 
SLURM release in May 2016 will have PMIx plugin.
What `PMIx_Init()/PMIx_Finalize()` signature I supposed to use there? The one from the stable 1.1.3 or the one from under-development 1.2.x?
The barrier inside PMIx_Finalize is not something that we **really need** since there is no problem in using it explicitly before calling PMIx_Fence() like I suggested in https://github.com/pmix/master/pull/50.
It is nice to have PMIx_Init options, but this can be done through additional pre-PMIx_Init function that won't brake API, i.e.:
```
PMIx_Inint_pre(libevent_handler);
PMIx_Init(<usual args>);
```
I am sorry that I missed last conf call - I was in the plane at the moment. and I was catching up after the trip so missed this PR. However I think that this PR having such important impact was merged too quickly.

**Comment by rhc54** [comment]
These things were discussed at some length, so it wasn't just done arbitrarily. The changes were tested against the SLURM plugin and do -not- break it. They actually work just fine, so I don't understand your concerns. In fact, the SLURM plugin now even works with backward compatibility, so things are okay.

**Comment by artpol84** [comment]
@rhc54 
Ahh, I see. Sorry. This was my misunderstanding. I've been out of context for a while and for some reasons thought that it's a server-side change.
No problems.
btw, who tested SLURM? And what do you mean by backward compatibility?

**Comment by rhc54** [comment]
@artpol84 No problems - glad you traveled safely! I tested SLURM using the unit tests as well as some MPI test programs from the latest OMPI master. I also debugged the PMI-1 and PMI-2 support and verified that those now work against the SLURM plugin.

**Comment by artpol84** [comment]
Thank you!
Thanks for testing SLURM! It's is nice to know that you can confirm that SLURM behaves!

**Pull request merged**
